; Generated by Auto-GUI 3.0.0
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Main: New
Gui Font, s9, Segoe UI
Gui Add, ListBox, x32 y16 w425 h134 0x50010081 , ...Loading list of disk...
Gui Add, ListBox, x32 y208 w425 h212 0x50010081 , ...Loading list of images...
Gui Add, Button, x288 y160 w80 h23 +Disabled  0x58012000 , Format Disk
Gui Add, Button, x32 y432 w80 h23 +Disabled  0x58012000 , Install image
Gui Add, CheckBox, x32 y165 w120 h20 0x50012003 , Show USB drives
Gui Add, Button, x376 y160 w80 h23 0x50012000 , Refresh Disks
Gui Add, DropDownList, x32 y459 w100 0x50010203 , UEFI Format|LEGACY Format
Gui Add, Text, x24 y504 w57 h23 0x50000200 , IP Address:
Gui Add, Text, x88 y504 w91 h23 0x50000200 
Gui Add, Button, x184 y504 w80 h23 0x50012000 , Renew IP
Gui Add, Text, x25 y531 w250 h23 0x50000200 , Version 0.14.0.4 - Copyright Miasik Jakub
Gui Add, Text, x120 y432 w200 h22 0x50000200 
Gui Add, Button, x376 y432 w80 h23 0x50012000 , Refresh Images
Gui Add, Button, x376 y464 w80 h23 0x50012000 , Load manually
Gui Add, Edit, x464 y16 w305 h536 +ReadOnly +Multi
Gui Add, Button, x340 y515 w120 h33 , Update App!`nto %wimLoaderVer%
Gui Show, w777 h558, WIM Loader
Return

MainGuiEscape:
MainGuiClose:
    ExitApp
