; Generated by Auto-GUI 3.0.0
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu, Options, Add, Open wim log, OpenWimlog
Menu, Options, Add, Open commands log, OpenWimlog
Menu, BarMenu, Add, Options, :Options
Menu, About, Add, Update App, UpdateApp
Menu, BarMenu, Add, About, :About
Gui, Menu, BarMenu
Gui Font, s9, Segoe UI
Gui Add, ListBox, x32 y16 w504 h147, DiskList
Gui Add, ListBox, x32 y208 w503 h225, ImagesList
Gui Add, Text, x25 y510 w83 h23 +0x200   , Version 1.0.0.0
Gui Add, Button, x32 y165 w80 h23, Format Disk
Gui Add, Button, x32 y432 w80 h23 +Default   , Load image
Gui Add, Button, x456 y165 w80 h23, Refresh Disks
Gui, Add, Radio, x32 y459 w70 h20 Checked vMode, UEFI
Gui, Add, Radio, x32 y+3 w70 h20, Legacy
Gui Add, Text, x25 y510 w250 h23 +0x200 , Text
Gui Add, Button, x456 y520 w100 h25, Update App!
Gui Font, s8
Gui Add, Button, x456 y432 w80 h30, Refresh Images
Gui Add, Button, x456 y465 w80 h23, Load manually
Gui Font
Gui Show, w563 h550, WIM Loader
Return

UpdateApp:
OpenWimlog:
return


GuiEscape:
GuiClose:
    ExitApp
