; Generated by Auto-GUI 3.0.0
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui +Resize
Gui Font, s9, Segoe UI
Gui Add, Edit, x8 y48 w736 h312 +ReadOnly +Multi
Gui Add, Text, x320 y16 w124 h27 +0x200, Updating Wim Loader

Gui Show, w753 h385, Autoupdate
Return

GuiEscape:
GuiClose:
    ExitApp
